micronaut:
  application:
    name: gateway
  server:
      port: 8080
consul:
    client:
        registration:
            enable: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"



            
      
