/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasus3NF;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class App {
    public static void main( String[] args ) throws SQLException {
        //create connection for a server installed in localhost, with a user "root" with no password
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3308/persewaan3nf", "root", null)) {
            // create a Statement
            try (Statement stmt = conn.createStatement()) {
                //execute query
                try (ResultSet result = stmt.executeQuery("SELECT nama from penyewa where id=1")) {
                    result.first();
                    System.out.println(result.getString("nama")+" menyewa: ");
                }
                
                try (ResultSet rs = stmt.executeQuery("SELECT movie.movie FROM `sewa` JOIN movie ON movie.id=sewa.id_movie WHERE sewa.id_penyewa=1")) {
                    //position result to first
//                    rs.first();
                     //result is "Hello World!"
                    while (rs.next()){
                    System.out.println(rs.getString("movie"));
                    }
                }
            }
        }
    }
}
//Executing: gradle build
//Arguments: [-c, D:\Project\dari-netbeans\Gradle\kasus3NF\settings.gradle]
//
//> Task :compileJava UP-TO-DATE
//> Task :processResources NO-SOURCE
//> Task :classes UP-TO-DATE
//> Task :jar
//> Task :startScripts
//> Task :distTar
//> Task :distZip
//> Task :assemble
//> Task :compileTestJava
//> Task :processTestResources NO-SOURCE
//> Task :testClasses
//> Task :test
//> Task :check
//> Task :build
//
//BUILD SUCCESSFUL in 25s
//7 actionable tasks: 6 executed, 1 up-to-date

//Executing: gradle :run
//Arguments: [-PmainClass=kasus3NF.App, -PcmdLineArgs=, -PjvmLineArgs=, -c, D:\Project\dari-netbeans\Gradle\kasus3NF\settings.gradle]
//
//> Task :compileJava UP-TO-DATE
//> Task :processResources NO-SOURCE
//> Task :classes UP-TO-DATE
//
//> Task :run
//Pirates of the Caribbean
//
//BUILD SUCCESSFUL in 3s
//2 actionable tasks: 1 executed, 1 up-to-date